version: "3"
services:
  db:
    image: public.ecr.aws/docker/library/postgres:14-alpine
    restart: always
    env_file:
      - ./.db.env
    ports:
      - "5432:5432"
    volumes: 
      - db-data:/var/lib/postgresql/data
  django:
    build: ./
    env_file:
      - ./.dev.env
      - ./.db.env
    volumes:
      - ./:/app
      - ./storage:/storage
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  redis:
    image: public.ecr.aws/docker/library/redis:6-alpine
    command: redis-server --requirepass "devpass"

volumes:
  db-data: